serverAddr = "127.0.0.1"
serverPort = 7200
auth.method = "token"
auth.token = "12345678"

[[proxies]]
name = "web"
type = "http"
#localIP = "127.0.0.1"
localPort = 80
customDomains = ["127.0.0.1"]
subdomain = "test"