bindPort = 7200
vhostHTTPPort = 8080
auth.method = "token"
auth.token = "12345678"
subDomainHost = "flowstack.io"

[[httpPlugins]]
name = "auth-manager"
addr = "127.0.0.1:9000"
path = "/handler"
ops = ["NewProxy"]